### ISSUE TITLE
Subscribe to event streams

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core-sidecar#2]
https://github.com/blockstack/blockstack-core/issues/1204

Capability to subscribe to core node events which include:
* Asset transfers, such as STX, names, and other NFTs/FTs
* Explicit Clarity log events

**Comment by jeffdomke** [comment]
@zone117x please add to 1266 and close

**Comment by zone117x** [comment]
The functionality required by this now comes from the main core-node socket stream as described at https://github.com/blockstack/blockstack-core/issues/1266
