### ISSUE TITLE
Retrieve smart contract source code and ABI

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core-sidecar#7]
On epoch notification, iterate all transactions for any new contract deployments. For each new contract, fetch the Clarity source code string and the contract ABI.

**Comment by zone117x** [comment]
TODO: stream this data via the sidecar socket if possible

**Comment by jeffdomke** [comment]
@zone117x please add to 1266 and close

**Comment by zone117x** [comment]
The functionality required by this now comes from the main core-node socket stream as described at https://github.com/blockstack/blockstack-core/issues/1266
